package main

import "fmt"

func printUsage() {
	fmt.Println("brag - Staff-level professional accomplishment tracker")
	fmt.Println()
	fmt.Println("Usage: brag <command> [options]")
	fmt.Println()
	fmt.Println("Commands:")
	fmt.Println("  init           Initialize brag system (sets role title and start date)")
	fmt.Println("  add            Add a new accomplishment entry")
	fmt.Println("  update <id>    Update basic fields of an existing entry")
	fmt.Println("  enrich         Add Staff-level metrics to existing entries")
	fmt.Println("  list           List entries (default: last 7 days)")
	fmt.Println("  report         Generate summary report for review prep")
	fmt.Println("  remove <id>    Remove an entry by ID")
	fmt.Println("  clear          Clear all entries (with confirmation)")
	fmt.Println("  export         Export entries to file (csv, json, txt)")
	fmt.Println("  config         Update configuration (e.g., role start date)")
	fmt.Println("  help [cmd]     Show detailed help for a command")
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  brag add                          # Interactive daily capture")
	fmt.Println("  brag add --week 1 -b Delivery ... # Backfill week 1 entry")
	fmt.Println("  brag enrich                       # Weekly synthesis flow")
	fmt.Println("  brag enrich --id 6                # Re-enrich specific entry")
	fmt.Println("  brag list --month 3               # View month 3")
	fmt.Println("  brag report --month 3             # Generate month 3 report")
	fmt.Println()
	fmt.Println("Run 'brag help <command>' for detailed usage.")
}

func printAddHelp() {
	fmt.Println("Usage: brag add [options]")
	fmt.Println()
	fmt.Println("Add a new accomplishment entry. Interactive by default.")
	fmt.Println()
	fmt.Println("Options:")
	fmt.Println("  -b string     Work context bucket (Delivery, Architecture, Process, Leadership)")
	fmt.Println("  -d string     Description of the work")
	fmt.Println("  -e string     Evidence URL (PR, Jira, Design Doc, Slack)")
	fmt.Println("  --start string  Start date (YYYY-MM-DD)")
	fmt.Println("  --end string    End date (YYYY-MM-DD)")
	fmt.Println("  --week int      Week number (relative to role start)")
	fmt.Println("  --month int     Month number (relative to role start)")
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  brag add")
	fmt.Println("    # Interactive prompts for bucket, description, evidence (defaults to today)")
	fmt.Println()
	fmt.Println("  brag add -b Delivery -d \"Shipped feature X\" -e \"https://...\"")
	fmt.Println("    # Quick add with flags (for scripting)")
	fmt.Println()
	fmt.Println("  brag add --week 1 -b Process -d \"Fixed CI bottleneck\" -e \"https://...\"")
	fmt.Println("    # Backfill an entry for week 1 of your role")
}

func printEnrichHelp() {
	fmt.Println("Usage: brag enrich [options]")
	fmt.Println()
	fmt.Println("Add Staff-level metrics to unenriched entries, or re-enrich existing entries.")
	fmt.Println()
	fmt.Println("Options:")
	fmt.Println("  --range string       Time range (e.g., 30d, 12w)")
	fmt.Println("  --id int             Enrich specific entry by ID")
	fmt.Println("  --pending            List unenriched entries without prompting")
	fmt.Println("  --hours string       Hours saved (e.g., 29.625, 90m, 2h)")
	fmt.Println("  --calc string        Calculation notes")
	fmt.Println("  --metric string      Business metric")
	fmt.Println("  --align string       Strategic alignment")
	fmt.Println("  --recognition string Peer recognition")
	fmt.Println("  --yes                Skip confirmation prompt")
	fmt.Println()
	fmt.Println("Enrichment Fields:")
	fmt.Println("  - Hours Saved (accepts: 1.5, 90m, 2h)")
	fmt.Println("  - Business Metric (e.g., \"Reduced latency by 200ms\")")
	fmt.Println("  - Strategic Alignment (e.g., \"Q2 OKR: Improve dev velocity\")")
	fmt.Println("  - Peer Recognition (e.g., \"Slack kudos from @manager\")")
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  brag enrich")
	fmt.Println("    # Find unenriched entries from last 7 days, prompt interactively")
	fmt.Println()
	fmt.Println("  brag enrich --id 6")
	fmt.Println("    # Re-enrich specific entry #6 (updates only fields you provide)")
	fmt.Println()
	fmt.Println("  brag enrich --pending")
	fmt.Println("    # List all unenriched entries without enriching")
	fmt.Println()
	fmt.Println("  brag enrich --id 2 --hours 29.625 --calc \"585 builds × 3 min\"")
	fmt.Println("    # Enrich entry #2 with flags (non-interactive)")
	fmt.Println()
	fmt.Println("  brag enrich --range 30d")
	fmt.Println("    # Enrich entries from last 30 days")
}

func printUpdateHelp() {
	fmt.Println("Usage: brag update <id> [options]")
	fmt.Println()
	fmt.Println("Update basic fields of an entry (bucket, description, evidence, dates).")
	fmt.Println("Does not affect enrichment data. Use 'brag enrich --id <id>' for that.")
	fmt.Println()
	fmt.Println("Options:")
	fmt.Println("  -b string       Work context bucket")
	fmt.Println("  -d string       Description")
	fmt.Println("  -e string       Evidence URL")
	fmt.Println("  --start string  Start date (YYYY-MM-DD)")
	fmt.Println("  --end string    End date (YYYY-MM-DD)")
	fmt.Println("  --week int      Week number (relative to role start)")
	fmt.Println("  --month int     Month number (relative to role start)")
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  brag update 3 -d \"New description\"")
	fmt.Println("    # Update just the description")
	fmt.Println()
	fmt.Println("  brag update 5 --week 2")
	fmt.Println("    # Change dates to week 2")
	fmt.Println()
	fmt.Println("  brag update 7 -b Architecture -e \"https://...\"")
	fmt.Println("    # Update bucket and evidence")
}

func printListHelp() {
	fmt.Println("Usage: brag list [options]")
	fmt.Println()
	fmt.Println("List accomplishment entries. Groups by bucket, shows tenure.")
	fmt.Println()
	fmt.Println("Options:")
	fmt.Println("  --range string  Time range (e.g., 30d, 12w)")
	fmt.Println("  --week int      Week number (relative to role start)")
	fmt.Println("  --month int     Month number (relative to role start)")
	fmt.Println("  --all           Show all entries")
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  brag list")
	fmt.Println("    # Last 7 days (default)")
	fmt.Println()
	fmt.Println("  brag list --month 3")
	fmt.Println("    # Entries from month 3 of your role")
	fmt.Println()
	fmt.Println("  brag list --all")
	fmt.Println("    # Everything since role start")
}

func printReportHelp() {
	fmt.Println("Usage: brag report [options]")
	fmt.Println()
	fmt.Println("Generate a summary report for review prep. Groups by bucket with totals.")
	fmt.Println()
	fmt.Println("Options:")
	fmt.Println("  --range string  Time range (e.g., 90d)")
	fmt.Println("  --week int      Week number")
	fmt.Println("  --month int     Month number")
	fmt.Println("  --year int      Year number")
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  brag report --month 3")
	fmt.Println("    # Summary of month 3 with entry count + hours saved per bucket")
	fmt.Println()
	fmt.Println("  brag report --year 1")
	fmt.Println("    # Full first year summary")
}

func printExportHelp() {
	fmt.Println("Usage: brag export [options]")
	fmt.Println()
	fmt.Println("Export entries to file. Supports csv, json, txt.")
	fmt.Println()
	fmt.Println("Options:")
	fmt.Println("  --format string  Export format (csv, json, txt) [default: csv]")
	fmt.Println("  --range string   Time range")
	fmt.Println("  --week int       Week number")
	fmt.Println("  --month int      Month number")
	fmt.Println("  --all            Export all entries")
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  brag export --format csv --month 3")
	fmt.Println("    # Export month 3 to ~/.config/eddie-brag/brag.csv")
	fmt.Println()
	fmt.Println("  brag export --format json --all")
	fmt.Println("    # Export everything to JSON")
}
